// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nflwheveqglnxgfmimpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbHdoZXZlcWdsbnhnZm1pbXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NDk3MTUsImV4cCI6MjA3OTMyNTcxNX0.mb1ZEOJtfbIZ2aaCG92zOtKYYmF-myoDghub_xh7jqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});